#!/bin/bash

RETVAL=0

echo "### SYNC"
rsync -av --exclude-from="sync-server.list" ~/Dev/givershop e-s-c-m@serverlan:/var/www/rails -e="ssh -p 2223"
if [ "$?" = "0" ]; then
   if [ "$1" != "-n" ]; then
      echo "### PRECOMPILE ASSETS"
      ssh -p 2223 e-s-c-m@serverlan 'cd /var/www/rails/givershop && rake assets:precompile'
      if [ "$?" != "0" ]; then
         echo !!! PRECOMPILE FAILED
         RETVAL=1
      fi
   fi
   if [ "$RETVAL" = "0" ]; then
      echo "### RESTART SERVER"
#      ssh -p 2223 root@serverlan 'apache2ctl restart'
      ssh -p 2223 root@serverlan '/etc/init.d/apache2 restart'
      if [ "$RETVAL" != "0" ]; then
         echo !!! RESTART FAILED
         RETVAL=1
      fi
   fi
else
   echo !!! SYNC FAILED
   RETVAL=1
fi
if [ "$RETVAL" = "0" ]; then
   echo "### DONE"
fi

